name: CI/CD PIPELINE

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
      
    defaults:
      run: 
        working-directory: . 

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint model.py
        
      - name: Run pytest
        run: pytest
    

